# Generated by Django 6.0.2 on 2026-02-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questonaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='c_id',
        ),
    ]
