# Generated by Django 6.0.3 on 2026-03-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questonaries', '0003_vote_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
