# Generated by Django 6.0.3 on 2026-04-04 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questonaries', '0004_alter_question_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='questonaries.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='hashtags',
            field=models.TextField(null=True),
        ),
    ]
