# Generated by Django 6.0.3 on 2026-04-09 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questonaries', '0005_question_cat_id_question_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/Ques_Covers/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Only this image formates are allowed: jpg, jpeg, gif, png, webp.')]),
        ),
    ]
