# Generated by Django 6.0.3 on 2026-03-31 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments_Likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsreply',
            old_name='commit',
            new_name='comment',
        ),
    ]
