# Generated by Django 6.0.3 on 2026-04-01 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments_Likes', '0002_rename_commit_commentsreply_comment'),
        ('questonaries', '0004_alter_question_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='CommentsLikes',
        ),
    ]
