# Generated by Django 6.0.3 on 2026-04-01 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comments_Likes', '0003_rename_likes_commentslikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentslikes',
            name='q_id',
        ),
        migrations.AddField(
            model_name='commentslikes',
            name='c_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Comments_Likes.comments'),
            preserve_default=False,
        ),
    ]
