# Generated by Django 6.0.3 on 2026-04-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments_Likes', '0006_folowers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folowers',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
